### PR TITLE
Add missing actions

### PR DESCRIPTION
**Pull request by michael-k**
We switched to awacs in the last couple of days and noticed some missing actions.  Instead of just adding the ones we found, we decided to scrape missing actions for services that exist in awacs from https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html#actions_table.

There's an unrelated change in `aws_marketplace.py`.  It can be reproduced by running the action generator on master.  I've put that in its own commit.

### Duplicate action for AWS Marketplace

Now that there's an *extra action* for `aws_marketplace`, the action generator puts `RegisterUsage` twice in `aws_marketplace.py`.  The reason is, that two AWS services ([AWS Marketplace](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awsmarketplace.html) and [AWS Marketplace Metering Service](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awsmarketplacemeteringservice.html)) are both in the same file.  The share the same prefix in the `policies.js` file that is used by the generator.  I've only included `RegisterUsage` once, but on the next run of the generator, the second one will appear again.

### Code Style (generator script)

I've noticed that multiple actions were on one line in the generator script up to a limit of 79(?) characters per line.  I've ignored that and put all actions in services that I've touched on its own line.  First of all that was way easier to script and sort.  And second of all it's what [black](https://pypi.org/project/black/) would have done (with exceptions).

### Scraper

I'll clean the script I've used to scape the documentation and provide it tomorrow.

### CODE REVIEW

**Comment by michael-k** [comment]
When I reran my script today, a few more missing actions appeared.  I've added them in a separate commit since you're squashing them anyway. :)

Here's the code I've used to scrape the actions: https://gist.github.com/michael-k/7fe360bc0c4f49b3fbb74999b6429099

**Comment by rtkjbillo** [comment]
Thanks for this - I was about to submit a PR for the missing iam:UpdateRole action, but looks like that (and much more) have been covered as part of your commits.

**Comment by michael-k** [comment]
@markpeek Can you review this PR?

**Comment by markpeek** [comment]
@michael-k wow...am I behind in reviewing awacs PR's and the awesome work you did to put together PR's #115 and #116. My biggest question is, when you say "we decided to scrape missing actions", what did you do to scrape them? As you may have noticed I was programmatically scraping AWS via this script but that site didn't have all this data. Are you doing this programmatically or manually?

**Comment by michael-k** [comment]
> what did you do to scrape them

I've linked the code in the second comment, it's available here: https://gist.github.com/michael-k/7fe360bc0c4f49b3fbb74999b6429099

> Are you doing this programmatically or manually?

A mixture.  I've installed awacs (or for later updates my branch) in a docker container or a virtual env.  Then I've ran the linked script.  It lists all the actions that are missing.  The manual part is to copy those over to `tools/gen.py`.

I've considered this a good enough approach to begin with.  It would be possible to integrate this into `tools/gen.py`, but I'd prefer to do this in a separate PR and you should be aware that it would massivelely slow down `tools/gen.py`.

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
