### PR TITLE
Generate awacs for Lambda

### PR DESCRIPTION
**Pull request by mhahn**
LMK if this should be called `awslambda` instead of just `lambda` to avoid overwriting `lambda` reserved name

### CODE REVIEW

**Comment by mhahn** [comment]
Went with just mirroring the behavior in troposphere

**Comment by Govinda-Fichtner** [comment]
@mhahn How do I work around this when I am still stuck with the old name?

```
from awacs.lambda import ARN as LAMBDA_ARN
```

I get the following error:

```
    from awacs.lambda import ARN as LAMBDA_ARN
                    ^
SyntaxError: invalid syntax
```

**Comment by mhahn** [comment]
you should be able to do something like:

```
import awacs
awslambda = getattr(awacs, 'lambda')
```

**Comment by mhahn** [comment]
just kidding... not working with python everyday anymore.

you'll need to use `importlib.import_module`, ie:

```
import importlib
awslambda = importlib.import_module('awacs.lambda')
```

lmk if that doesn't work

**Comment by markpeek** [comment]
@mhahn I just pushed a branch (referenced above) that should fix this issue. Can you review?

**Comment by mhahn** [comment]
@markpeek 👍 thanks!

**Pull request closed without merging**
